version: '3'
services:
  bot:
    build: .
    restart: always
    environment: 
        BOT_KEY: ${ano_ojosama_bot:-default} #"<DISCORD_BOT_KEY>"
        #TEMP_RAM_SIZE: "256m"
    volumes: 
    - ./src:/src
    #privileged: true
