version: '3'
services:
  bot:
    image: ghcr.io/penguincabinet/anonymous-ojosama-bot/docker:latest
    restart: always
    environment: 
        BOT_KEY: ${ano-ojosama-bot:-default} #"<DISCORD_BOT_KEY>"
        #TEMP_RAM_SIZE: "256m"
    volumes: 
    - ./src:/src
    #privileged: true
